# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.BaseModel')),
                ('Name', models.CharField(max_length=200)),
                ('Host', models.GenericIPAddressField()),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('DefaultDatabase', models.CharField(max_length=200)),
            ],
            bases=('dashboard.basemodel',),
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.BaseModel')),
                ('Name', models.CharField(max_length=200)),
                ('Text', models.CharField(max_length=1000)),
            ],
            bases=('dashboard.basemodel',),
        ),
    ]
