# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='host',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
    ]
