# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_connection_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Connection'),
        ),
    ]
