# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_query_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='text',
            field=models.TextField(),
        ),
    ]
