# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170730_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='visualization_type',
            field=models.CharField(choices=[(b'0', b'discreteBarChart'), (b'2', b'junior'), (b'3', b'senior'), (b'1', b'sophomore')], max_length=1, null=True),
        ),
    ]
