# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170730_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
