# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170730_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='x_axis_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
